#!/bin/bash

set -e

buildsome="$(stack exec -- which buildsome) $@"

cd $(dirname $(realpath $0))

${buildsome} -f implicitphony
git clean -fdx -- implicitphony

${buildsome} -f dlopen
${buildsome} -f dlopen
git clean -fdx -- dlopen

# Failing:
#
# ifs/test ${buildsome}
# git clean -fdx -- ifs

${buildsome} -f implicitpat
${buildsome} -f implicitpat
git clean -fdx -- implicitpat

${buildsome} -f par -j4 && (echo Failure expected ; exit 1)
${buildsome} -f par -j4 && (echo Failure expected ; exit 1)
git clean -fdx -- par

remove_pattern_target/test ${buildsome}
git clean -fdx -- remove_pattern_target

scratch/run_tests ${buildsome}
git clean -fdx -- scratch

duplicate_pattern/test ${buildsome}
git clean -fdx -- duplicate_pattern

${buildsome} -f stat
${buildsome} -f stat
git clean -fdx -- stat

wrongparorder/test ${buildsome}
git clean -fdx -- wrongparorder

# Failing:
#
# ${buildsome} -f overpar
# ${buildsome} -f overpar
# git clean -fdx -- overpar

${buildsome} -f atfuncs
${buildsome} -f atfuncs
git clean -fdx -- atfuncs

speculative_error/test ${buildsome}
git clean -fdx -- speculative_error

# Failing:
#
# compat_makefile/test ${buildsome}
# git clean -fdx -- compat_makefile

pyc/test ${buildsome}
git clean -fdx -- pyc

cache/test ${buildsome}
git clean -fdx -- cache

meddling/test ${buildsome}
git clean -fdx -- meddling

echo PASSED ALL TESTS
${buildsome} --version
