#!/bin/bash -eu
buildsome=${1:-buildsome}

cd $(dirname $0)
touch should_be_deleted_by_make_dependency
$buildsome -M --overwrite
$buildsome clean

#TODO: addition of escape_input awaits fix #97
FILES="out/foo.o moshe.a moshe.a.b should_be_deleted_by_make" # escape_input
for f in $FILES
do
    test ! -e $f || (echo "ERROR: file: $f was not deleted by buildsome clean?!" && exit 1)
done

echo "not # bla" > should_be_deleted_by_make
# without the sleep here, at least on my machine the two files have exactly the same mtime. not sure why!
# 18:33:56.602501780 +0300 should_be_deleted_by_make
# 18:33:56.602501780 +0300 should_be_deleted_by_make_dependency
sleep 0.1
touch should_be_deleted_by_make_dependency

make -f compat-makefile

for f in $FILES
do
    test -e $f || (echo "ERROR: file: $f was not created during make/build?!" && exit 1)
done

diff -u ./should_be_deleted_by_make <(echo "# bla") || (echo 'ERROR: should_be_deleted_by_make was not deleted before build?!' && exit 1)
