* Warnings about makefile (over-specified outputs, etc) to carry makefile position information

* Dump include stack when reporting errors

* {} expansions after variable expansions

* Enumerate pattern outputs (wildcards, container dir of patterns)
