* Variable assignment should not expand variables, only recursively do so later at var expansion

* {} expansions after variable expansions

* Enumerate pattern outputs (wildcards, container dir of patterns)
