* Disallow "" in include, like make

* Use cwd/default as default target, instead of first target

* Oops: includes will leak variables?!

* Dump include stack when reporting errors

* {} expansions after variable expansions

* Enumerate pattern outputs (wildcards, container dir of patterns)
